config/routes.rb
Rails.application.routes.draw do
  resources :boards

  root "static_pages#home", page: "home"
  get 'static_pages/home'
  get 'static_pages/x3'
  post 'static_pages/x3'
  get 'static_pages/tic_tac_toe'
  get 'static_pages/cv'
  get 'static_pages/move'
  get 'static_pages/about'
end

app/models/board.rb
class Board < ActiveRecord::Base
include AASM
  aasm  column: 'state' do
    state :waiting, :initial => true
    state :playing
    state :endedplayer
    state :endedcpu
    state :endedtie

    event :start do
      transitions :from => :waiting, :to => :playing
    end

    event :wonplayer do
      transitions :from => :playing, :to => :endedplayer
    end
    event :woncpu do
      transitions :from => :playing, :to => :endedcpu
    end
    event :tie do
      transitions :from => :playing, :to => :endedtie
    end
  end

	def next_move(row, column)
		board= JSON.parse(state_ids)
		self.start if self.waiting?
		if board[row][column].nil?
			board[row][column]= 1
		end
		make_move(board)
	end

private
	def check(board,initial_row, initial_col, add_row, add_col)
			@player1=0
			@cpu=0
			saved_row= 0
			saved_col= 0
			row= initial_row
			column= initial_col
			blocked_play= false
			blocked_cpu= false
			@max.times do
				if board[row].nil? || board[row][column].nil? || (board[row][column] == 0)
					saved_row= row
					saved_col= column
				end
				if !(board[row].nil? || board[row][column].nil?)
					if board[row][column]==1
						@player1= @player1 + 1
						blocked_cpu= true
					end
					if board[row][column]==2
						@cpu= @cpu + 1
						blocked_play= true
					end
				end
				row= row + add_row
				column= column + add_col
			end
			@game_ended= (@player1 == @max) || (@cpu == @max)
			if !@game_ended && (!blocked_play && (@player1 > @max_play) || (!blocked_cpu && (@cpu > @max_play) && ((@player1 < @cpu) )))
				@max_row= saved_row
				@max_col= saved_col
				if !blocked_play && (@player1 > @max_play)
					@max_play= @player1
				elsif !blocked_cpu && (@player1 < @cpu) && (@cpu > @max_play)
					@max_play= @cpu
					@game_won= (@cpu + 1) == @max
				end
			end
	end
	def make_move(board)
		@max_play= 0
		@max_col= 0
		@max_row= 0
		@max= board.size
		column= 0
		@game_ended= false
		@game_won= false
		while !@game_ended && (column < @max)
			check(board,0, column, 1, 0)
			column= column + 1
		end
		row= 0
		while !@game_ended && (row < @max)
			check(board,row, 0, 0, 1)
			row = row + 1
		end
		check(board,0, 0, 1, 1) unless @game_ended

		check(board,0,@max-1, 1, -1)  unless @game_ended

		if  !@game_ended && (( board[@max_row].nil? || board[@max_row][@max_col].nil?) || board[@max_row][@max_col] < 1 )
			if (@max_play == 1) && (( board[@max/2].nil? || board[@max/2][@max/2].nil?) || board[@max/2][@max/2] < 1 )
				board[@max/2][@max/2]= 2
			else
				board[@max_row][@max_col]= 2
			end
		elsif !@game_ended && (board[@max_row][@max_col] >= 1)
			self.tie
		end
		self.woncpu if @game_won
		self.wonplayer if !@game_won && @game_ended
		self.state_ids= board.to_json
		self.save if self.changed?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:state_ids, :color)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	require 'json'

	def cv
		@page_name == 'json_to_html'
		file= File.read('app/assets/javascripts/cv.json')
		@file= JSON.parse(file)

		respond_to do |format|
			format.html
			format.json do
				temp_file = Tempfile.new([' ', '.json'], :encoding => 'ascii-8bit')
					temp_file.write(file)
					temp_file.rewind
					send_file (temp_file), disposition: 'attachment'
				end
		end
	end

	def tic_tac_toe
		@page_name == 'tic_tac_toe'
	end

	def x3
		@page_name == 'tic_tac_toe'
		@max= params[:board_size]
		if !@max.nil?
			Board.delete(session[:current_game])
			session[:current_game]= nil
			@max= @max.to_i
		end
		if (session[:current_game].nil?)
			@board= (Array.new(@max) { Array.new(@max) })
			@b= Board.create(state_ids: @board.to_json, color: "blue")
			session[:current_game]||= @b.id
		else
			@b= Board.where(id:session[:current_game]).first
			if !@b.nil?
				@board= JSON.parse(@b.state_ids)
				size= @board.size
				@max= size
			else
				size= nil
			end
			if size != @max
				@board= (Array.new(@max) { Array.new(@max) })
				@b= Board.create(state_ids: @board.to_json, color: "blue")
				session[:current_game]= @b.id
			end
		end
	end

	def move
		cell= params[:id]
		b= Board.find(session[:current_game])
		b.next_move((cell.to_i%10), (cell.to_i/10))
		@b = b
		@board= JSON.parse(b.state_ids)
		@max= @board.size
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyphicon(icon, options = {})
    options.merge! class: "glyphicon #{icon} #{options[:class]}"
    content_tag :span, nil, options
  end

  def awesomeicon(icon, options = {})
    options.merge! class: "pe-7s-#{icon} #{options[:class]}"
    content_tag :i, nil, options
  end
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state_ids %><br>
    <%= f.text_field :state_ids %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Id</th>
            <th>Array State</th>
            <th>Game State</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
    <tbody>
      <%= content_tag_for(:tr, @boards) do |board| %>
            <td><%= board.id %></td>
            <td><%= board.state_ids %></td>
            <td><%= board.state %></td>
            <td class="text-right">
              <%= link_to glyphicon('glyphicon-eye-open'),
                board_path(board), class: 'btn btn-primary btn-xs' %>
              <%= link_to glyphicon('glyphicon-pencil'),
                edit_board_path(board), class: 'btn btn-primary btn-xs' %>
              <%= link_to glyphicon('glyphicon-trash'),
                board, method: :delete, data: { confirm: 'Are you sure?' },
                class: 'btn btn-xs btn-danger' %>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State ids:</strong>
  <%= @board.state_ids %>
</p>

<p>
  <strong>Color:</strong>
  <%= @board.color %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="copyright pull-right">
  &copy; 2018 <a href="">Bienvenido</a> Pagina de prueba
  </p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= @title %></a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">

        </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar" data-color="green" data-image="<%= image_path "sidebar-5.jpg" %>">
  <div class="sidebar-wrapper">
    <div class="logo">
      <a href="\" class="simple-text">
        WELCOME
      </a>
    </div>
     <ul class="nav">
      <li class= <%= (@page_name == 'cv') ? 'active' : '' %> >
          <%= link_to '/static_pages/cv' do %>
            <%= awesomeicon('id') %>
            <p>
              Curriculum Vitae
            </p>
          <% end %>
      </li>
      <li class= <%= (@page_name == 'tic_tac_toe') ? 'active' : '' %> >
          <%= link_to '/static_pages/tic_tac_toe' do %>
            <%= awesomeicon('joy') %>
            <p>
              Tic Tac Toe
            </p>
          <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href= "<%= image_path "favicon.ico" %>" >
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>CV</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css' rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>      

  <div class="wrapper">
    <%= render 'layouts/sidebar' %>
    <div class="main-panel">
      <%= render 'layouts/header' %>
      <div class="content">
        <div class="container-fluid row">
          <div class="card">
            <div class="content">
              <%= content_tag :div, notice, class: 'alert alert-success', role: 'alert' if notice %>
              <%= content_tag :div, alert, class: 'alert alert-danger', role: 'alert' if alert %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/cv.html.erb
<div class="jumbotron">
	<h1>Curriculum Vitae</h1>
	<p> Rendered from parsed <b>JSON</b> -  <%= link_to 'Download file', '/static_pages/cv.json' %></p>
</div>

<% @file.each do |line| %>
	<h3>
		<%= line[0] %>
	</h3>
	<% line[1].each do |key, value| %>
		<% if value.is_a? Array  %>
			<% value.each do |l| %>
				<p> <%= l %> </p>
			<% end %>
			
		<% else %>
			<p><b><%= key + ": " %></b> <%= value %></p>
		<% end %>
	<% end %>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
<h1>Welcome!</h1>
<p><b> See the sidebar for cool stuff</b></p>
</div>

app/views/static_pages/move.js.erb
$('#result').html('<%= @b.aasm.human_state %>');
<% row= 0 %>
<% @max.times do %>
	<% column= 0 %>
	<% @max.times do %>
		<% case (@board [row][column]) %>
			<% when 1 %>
				$('#<%= column.to_s + row.to_s %>').removeClass('btn-primary');
				$('#<%= column.to_s + row.to_s %>').addClass('btn-info');
				$('#<%= column.to_s + row.to_s %>').off('click');
			<% when 2 %>
				$('#<%= column.to_s + row.to_s %>').removeClass('btn-primary');
				$('#<%= column.to_s + row.to_s %>').addClass('btn-danger');
				$('#<%= column.to_s + row.to_s %>').off('click');
		<% end %>
		<% column= column + 1 %>
	<% end %>
	<% row= row + 1 %>
<% end %>

app/views/static_pages/tic_tac_toe.html.erb
<div class="jumbotron">
	<h1>Tic Tac Toe</h1>
<p> Enter the size of the Board </p>
<%= form_tag static_pages_x3_path, class: 'form-horizontal' do %>
  <div class="form-group">
    <%= label_tag :board_size, 'Board Size', class: 'col-md-4 control-label' %>
    <div class="col-md-4">
    	<%= number_field_tag :board_size, nil, min: 2 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-9">
      <%= submit_tag 'Create Board', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

</div>
<% if !(session[:current_game]).nil? && !(Board.where(id:session[:current_game]).first.nil?) %>
	<%= link_to awesomeicon('diskette') + ' CONTINUE GAME','/static_pages/x3', class: 'btn btn-success', title: 'Continue playing the last game', data: { toggle: 'tooltip', placement: 'right' } %>
<% end %>

app/views/static_pages/x3.html.erb
<div class="jumbotron">
	<h1>Tic Tac Toe</h1>
<p> Done using <b>Ruby</b> (logic), <b>Rails</b> (remote), <b>JQuery</b> (update board),a <b>Database (PostgreSQL for boards states)</b> and a session variable (for the board Id).</p>
<p>Board size = <%= @max %></p>

</div>

<% column= 0 %>
<% @max.times do %>
	<% row= 0 %>
	<p>
		<% @max.times do %>
		<% new_name= column.to_s + row.to_s %>
		<% state= @board[row].nil? ? 0 : (@board[row][column]).to_i %>
		<% color=  (state == 0) ? "primary" : ((state == 1) ? "info" : "danger") %>
			<%= link_to "-", static_pages_move_path(id: new_name), class: 'board btn btn-lg btn-' + color, remote: true, id: new_name %>
			<% row= row + 1 %>
		<% end %>
	</p>
	<% column = column + 1%>
<% end %>
<h1 id= "result"><%= @b.aasm.human_state %><h1>
<%= link_to "New Game", static_pages_tic_tac_toe_path, class: 'btn btn-lg btn-primary', title: 'New game', data: { toggle: 'tooltip' } %>